# Generated by Django 4.2.7 on 2024-02-02 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import perfiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('desc', models.CharField(max_length=100, verbose_name='Descripción')),
                ('vcf_file', models.FileField(blank=True, null=True, upload_to='vcf_files/', verbose_name='Archivo VCF')),
                ('links', models.TextField(blank=True, null=True, verbose_name='Links')),
                ('telefonos', models.TextField(blank=True, null=True, verbose_name='Teléfonos')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.OneToOneField(default=perfiles.models.default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LinkImg', models.ImageField(upload_to='img/', verbose_name='User_Link_Image')),
                ('LinkName', models.CharField(max_length=100, verbose_name='User_Link_Name')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.perfiles')),
            ],
            options={
                'verbose_name': 'User_Image',
                'verbose_name_plural': 'User_Image',
            },
        ),
    ]
